#%RAML 1.0 ResourceType

uses:
  common: /common/library.raml

get:
  description: Get the list of locations for a server
  responses:
    200:
      body:
        application/json:
          type: array
          items:
            type: object
            properties:
              location_id:
                type: common.Uuid
                description: Location ID
              name:
                type: string
                description: Human-readable name that will be displayed to the users
              infras:
                type: array
                items:
                  type: object
                  properties:
                    infra_id:
                      type: common.Uuid
                      description: Infrastructure component ID
                    name:
                      type: string
                      description: Human-readable name that will be displayed to the users
                    capabilities:
                      type: string[]
                      description: Infrastructure component capabilities
                description: Infrastructure components
          example: !include ../examples/get_locations_response.json
