#%RAML 1.0 Library

#
# @Copyright © 2003-2019 Acronis International GmbH. This source code is distributed under MIT software license.
#

types:
  Id: !include types/Id.raml
  Uuid: !include types/Uuid.raml
  Error: !include types/Error.raml
  Version: !include types/Version.raml
  # dictionaries
  DictStrings: !include types/DictStrings.raml
  DictInfo: !include types/DictInfo.raml
  # cloud types
  ResourceType: !include types/ResourceType.raml
  ApplicationType: !include types/ApplicationType.raml
  TenantKind: !include types/TenantKind.raml
  UserRole: !include types/UserRole.raml
  MeasurmentUnit: !include types/MeasurmentUnit.raml
  QuotaValue: !include types/QuotaValue.raml
  Status: !include types/Status.raml
