#%RAML 1.0 ResourceType

#
# @Copyright © 2003-2019 Acronis International GmbH. This source code is distributed under MIT software license.
#

uses:
  common: /common/library.raml

post:
  description: Create a group of configurable options
  body:
    application/json:
      type: object
      properties:
        name:
          type: string
          description: Human-readable name that will be displayed to the users
        description?:
          type: string
          description: Human-readable description that will be displayed to the users
        server_id:
          type: common.Id
          description: Server ID
        edition?:
          type: string
          description: Edition name
      example: !include ../examples/create_group_request.json
  responses:
    200:
      body:
        application/json:
          type: object
          properties:
            id:
              type: common.Id
              description: Group ID
          example: !include ../examples/create_group_response.json
    400:
      description: The request has invalid properties
      body:
        application/json:
          type: common.Error
          example: !include ../examples/create_group_error_400.json
