#%RAML 1.0 DataType

uses:
  common: /common/library.raml

description: All available notifications
type: object
properties:
  application_type: common.ApplicationType
  items:
    type: array
    items:
      type: object
      properties:
        type:
          description: Key for the notification name, machine readable
          type: string
        status:
          description: Is notification enabled for user
          type: common.Status
