#%RAML 1.0 Trait

uses:
  common: /common/library.raml

responses:
  401:
    description: Lacks valid authentication credentials for Cloud
    body:
      type: common.Error
      example: !include ../examples/traits/error_401.json
