#%RAML 1.0 Trait

#
# @Copyright © 2003-2019 Acronis International GmbH. This source code is distributed under MIT software license.
#

uses:
  common: /common/library.raml

responses:
  401:
    description: Lacks valid authentication credentials for Cloud
    body:
      type: common.Error
      example: !include ../examples/traits/error_401.json
