#%RAML 1.0 Trait

#
# @Copyright © 2003-2019 Acronis International GmbH. This source code is distributed under MIT software license.
#

uses:
  common: /common/library.raml

queryParameters:
  server_id:
    type: integer
    minimum: 1
responses:
  400:
    description: The query parameter has invalid format
    body:
      type: common.Error
      example: !include ../examples/traits/error_400.json
  404:
    description: Cannot find the server
    body:
      type: common.Error
      example: !include ../examples/traits/error_404.json
