#%RAML 1.0 DataType

#
# @Copyright © 2003-2019 Acronis International GmbH. This source code is distributed under MIT software license.
#

type: object
properties:
  # https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#additional-properties
  //:
    type: object
    properties: 
      title: string
      description?: string
