#%RAML 1.0 Trait

#
# @Copyright © 2003-2019 Acronis International GmbH. This source code is distributed under MIT software license.
#

uses:
  common: ../library.raml

responses:
  415:
    description: Required type in 'Accept' request header is not supported
    body:
      type: common.Error
      example: !include ../examples/traits/error_415.json
