#%RAML 1.0 DataType

#
# @Copyright © 2003-2019 Acronis International GmbH. This source code is distributed under MIT software license.
#

uses:
  common: /common/library.raml

type: object
properties:
  type:
    type: string
    description: Application type
  status:
    type: common.Status
    description: Status
  editions:
    type: array
    items:
      type: !include Edition.raml
    description: The list of supported editions
  offering_items:
    type: array
    items:
      type: !include OfferingItem.raml
    description: The list of supported offering items
