#%RAML 1.0 DataType

#
# @Copyright © 2003-2019 Acronis International GmbH. This source code is distributed under MIT software license.
#

uses:
  common: /common/library.raml

type: object
properties:
  name:
    type: string
    description: Edition name
  status:
    type: common.Status
    description: Status
