#%RAML 1.0 ResourceType

#
# @Copyright © 2003-2019 Acronis International GmbH. This source code is distributed under MIT software license.
#

uses:
  common: ../library.raml

get:
  description: Get localizations for cloud items (like applications, offering items etc)
  responses:
    200:
      body:
        application/json:
          type: object
          properties:
            applications: common.DictInfo
            editions: common.DictInfo
            offering_items: common.DictStrings
            notifications: common.DictStrings
          example: !include ../examples/l10n_response.json
